services:
  - type: web
    name: studyverse
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class gevent -w 2 --worker-connections 1000 --timeout 120 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
